# Generated by Django 4.1.7 on 2023-03-15 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='RegisteredCustomer',
        ),
    ]
